dashboard:
  settings:
    SECRET_KEY: YOUR SECRET KEY
    units:
      output:
        temp: fahrenheit
        speed: mph
        rainfall: inches
      input:
        temp: celsius
        speed: km/h
        rainfall: mm
    mongoDBString: raspberryweather.local
    mongoDB:
      windDirection: windAverage
      recentSpeed: recentSpeed
      avgWindSpeed: windSpeedAverage
      windGust: windGust
      rainfall: rainfall
      humidity: humidity
      pressure: pressure
      ambientTemp: ambientTemp
      groundTemp: groundTemp
  quickLook:
    format:
      windDirection: txt
    periods:
      windDirection: 30
      avgWindSpeed: 360
      windGust: 720
      rainfall: 720
      humidity: 30
      pressure: 30
      ambientTemp: 30
      groundTemp: 30
  sensors:
    windDirection: true
    windSpeed: true
    rainfall: true
    humidity: true
    pressure: true
    ambientTemp: true
    groundTemp: false
