dashboard:
  settings:
    # ----------------------
    # Miscellaneous settings
    #  ---------------------
    SECRET_KEY: 'YOUR SECRET KEY'
    apiURL: API URL
    units:
      temp: celsius
      speed: km/h
      rainfall: mm

  quickLook:
    format:
      # ------------------------------------
      # How data is to be presented and formatted
      # on the page
      # Recommended values are default
      # ------------------------------------
      windDirection: txt # txt = Text Based Info, img = Compass Image Info

    periods:
      # ------------------------------------
      # Periods of displaying quicklook data.
      # All data points are variable.
      # Recommended values are default.
      # ------------------------------------
      windDirection: 30 # measured in minutes
      avgWindSpeed: 360 # measured in minutes
      windGust: 720 # measured in minutes
      rainfall: 720 # measured in minutes
      humidity: 30 # measured in minutes
      pressure: 30 # measured in minutes
      ambientTemp: 30 # measured in minutes
      groundTemp: 30 # measured in minutes

